name: LaRoberta

model:
  model_name: roberta-base
  freeze_encoder: true
  linear_size: [256, 128]

tokenizer:
  max_length: 200
  padding: true
  truncation: longest_first
  return_tensors: pt

train:
  input_opts:
    return_attn: true
  output_opts:
    pass_attn: true
