name: AttentionRNN

model:
  hidden_size: 256
  num_layers: 1
  linear_size: [256, 128]
  dropout: 0.5
  max_length: 200
  emb_trainable: false
  emb_size: 300
  emb_init: data/AmazonCat/emb_init.npy  # AmazonCat-1000

train:
  input_opts:
    return_attn: true
  gen_input_opts:
    pass_attn: true
    rnn_training: true
  last_input_opts:
    pass_attn: true
