name: AttentionRNN

model:
  hidden_size: 150
  num_layers: 1
  linear_size: [256]
  dropout: 0.5
  emb_trainable: false
  emb_size: 300

train:
  input_opts:
    return_attn: true
  output_opts:
    pass_attn: true
