name:
  base_encoder: RNNEncoder
  matcher: AttentionRNN2
  encoder: AttentionRNNEncoder2

base_encoder:
  emb_size: 300
  hidden_size: 384
  num_layers: 1
  emb_trainable: false
  dropout: 0.5

matcher:
  hidden_size: 768  # encoder.hidden_size x 2
  linear_size: [256]

encoder:
  hidden_size: 768  # encoder.hidden_size x 2
  num_heads: 3
