name: CornetAttentionRNN

model:
  hidden_size: 256
  num_layers: 1
  linear_size: [256]
  cor_context_size: [1000, 1000]
  dropout: 0.5
  max_length: 500
  emb_trainable: false
  emb_size: 300
  emb_init: data/EURLex4K/emb_init.npy  # EURLex-4K

train:
  input_opts:
    return_attn: true
  gen_input_opts:
    pass_attn: true
    rnn_training: true
  last_input_opts:
    pass_attn: true
