name: EaseAttentionRNN

model:
  hidden_size: 256
  num_layers: 1
  linear_size: [256]
  dropout: 0.5
  max_length: 500
  emb_trainable: false
  emb_size: 300
  lamda: 500
  random_init: false
  adj_trainable: false
