name: FCNet

model:
  linear_size: [512, 256]
  input_size: 21531  # RCV1

train:
  input_opts:
    return_hidden: true
  gen_input_opts:
    pass_hidden: true
  last_input_opts:
    pass_hidden: true
