name: LabelGCNAttentionRNNv4

model:
  hidden_size: 256
  label_emb_size: 300
  num_layers: 1
  linear_size: [256]
  dropout: 0.5
  max_length: 500
  emb_trainable: false
  emb_size: 300
  lamda: 500
  random_init: false
  gcn_hidden_size: [300, 300]
  gcn_dropout: 0.3
  top_adj: 1e-4
  use_b_weights: true
  label_emb_init: true
  gcn_adj_trainable: false
  use_gat: true
  # gcn_adj_dropout: 0.7
