name: LabelGCNAttentionRNNv5

model:
  hidden_size: 256
  label_emb_size: 256
  num_layers: 1
  linear_size: [256]
  dropout: 0.5
  max_length: 500
  emb_trainable: false
  emb_size: 300
  lamda: 500
  random_init: false
  gcn_hidden_size: [300, 300]
  gcn_dropout: 0.3
  top_adj: 1e-4
  use_b_weights: true
  emb_init: data/EURLex4K/emb_init.npy  # EURLex-4K

train:
  input_opts:
    return_attn: true
  gen_input_opts:
    pass_attn: true
    rnn_training: true
  last_input_opts:
    pass_attn: true
