name: LaRoberta4Mix

model:
  model_name: roberta-base
  freeze_encoder: false
  linear_size: [256, 128]

tokenizer:
  max_length: 300
  padding: true
  truncation: longest_first
  return_tensors: pt

train:
  input_opts:
    return_attn: true
  output_opts:
    pass_attn: true
